server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/rendezvous/**
        - id: prescription-service
          uri: lb://prescription-service
          predicates:
            - Path=/api/prescriptions/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
